AlenaMushko/Filmoteka_teamwork

src/my_library.html
Вибач вчора забула про другу сторінку
=> Fonts to my library

src/partials/library-header.html, src/scss/components/_button.scss
=> btn and btn__modal

src/js/modal.js, src/partials/modal.html, src/scss/components/_modal.scss
Вніс всі зміни, про які говорили на мітапі і додав можливість закривати модалку по Esc.
=> fixed modal html css and js files

src/js/functionsForFilms.js, src/js/pagination.js, src/js/refs.js, src/js/searchFilms.js
Added working pagination, refsб and commented some not working code.
=> Working pagination

src/js/slideRevenueFilms.js, src/partials/slider-new-films.html, src/scss/layout/_section-slider-new-films.scss
поки так завтра ще пошукаю як той заголовок додати
=> styless for slider

src/library.js
=> footer modal on

src/js/getTrailers.js
Не можу інакше стягнути собі всі зміни з мейна поки не запушу свою гілку... Може я щось не вірно роблю. Тут тільки кусок коду
=> Create getTrailers.js Work in progress

src/scss/components/_modalRegistration.scss, src/scss/layout/_section-slider-new-films.scss
Взарась за ту модалку, так ноут сів, потім ще кусок скину(((
=> modal inputs log in style

src/index.js, src/js/localStorage.js, src/js/manipulate-modal-film-content.js
розкоментувати в кінці файлу індекс.джиес  і все повинно працювати
=> Dmytro  local storage 1

src/index.html, src/index.js, src/js/changeTheme.js, src/library.js, src/my_library.html, src/partials/home-header.html, src/scss/components/_pagination.scss, src/scss/layout/_layout.scss, src/scss/layout/_themeDark.scss
Зробила підключення в обидва js файли. Додала id та value на кнопку в хедері (можливі конфлікти з Павлом). Додала стилізацію пагінації.  Треба перевірити чи запрацює на гіті.
=> Filmoteka theme switch scss file

src/partials/library-section-films.html
=> fixed to top in my library

src/js/functionsForFilms.js, src/js/menuFilters.js, src/js/pagination.js, src/js/searchFilms.js
Пагінація працює без додаткових запитів. Прошу перевірити на гіті.
=> Pafination filters attempt3

src/index.js, src/js/auth.js, src/js/firebaseDatastorage.js, src/js/headerBtnLinkLogic.js, src/library.js
Please, uncomment index.js and library js.
=> Feature:  authorisation for existant users

add data-lang.txt, src/partials/home-header.html, src/partials/library-header.html
виправив косяк який не давав розгортатись сторінці
=> add data-lang on header and data-set in button lang

src/js/changeTheme.js, src/library.js
=> resolve bag

src/js/getTrailers.js, src/js/modal.js
=> Styling trailers0

package-lock.json, package.json, src/index.html, src/js/getTrailers.js, src/js/modal.js
Попроси всіх зрообити npm install пліз, бо я додав нову лібу для модалки для трейлеру
=> Додав basiclightbox лібу

src/scss/layout/_section-slider-new-films.scss
=> slide margin move

src/partials/modal-registration.html, src/partials/slider-new-films.html, src/scss/layout/_section-slider-new-films.scss
Фіксована висота контейнера закоментована бо в мене на локалі відбувається це випадання за контейнер і тоді картинки наїжджають на другій сторінці на картинку заглушки
=> Slider container and login language

src/partials/slider-new-films.html
Змінила h1  на h2 бо в контейнері є h1. і додала дата  атрибут який кудись дівся
=> change h1 to h2

src/scss/components/_button.scss, src/scss/layout/_section-slider-new-films.scss
Додала транзішин, змінила позиціонування тексту, і додала курсор поінтер на кнопки
=> add tratsition and change text position
